### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by nervjack2** [utter-project/fairseq#2]
Hi,
I would want to ask how to install the dependencies?
Is it identical to original fairseq?
I run `pip install --editable ./` and it stuck at "Installing build dependencies ...". 
Thanks!

**Comment by mzboito** [comment]
Hello,

Yes, it should be possible to install it just like fairseq (as you mentioned pip install -e .).
Are you sure the process is really stuck? 
I ask because I remember sometimes the installation would be very very slow (between 10-20min). I don't know why!

**Comment by nervjack2** [comment]
It successfully install after 30 min, thank you so much!
